### ISSUE TITLE
While defining remote relationship, using _and in where is not working

### ISSUE THREAD

**Issue by nizar-m** [tirumaraiselvan/graphql-engine#53]
For example, defining remote relationship like this fails
```yaml
 remote_field:
    hge_remote_baseball_action_plays:
      arguments:
        where:
          _and:
          - baseball_event_state_id:
              _eq: $id
          - _not:
              baseball_event_state_id:
                _neq: $id
```
with error:
```json
  "path": "$.args.remote_relationships[0]",
  "error": "UnsupportedMultipleElementLists :| []",
  "code": "remote-schema-error"
```
