### ISSUE TITLE
From console, create a remote relationship with _and in where fails

### ISSUE THREAD

**Issue by nizar-m** [tirumaraiselvan/graphql-engine#54]
The console generates the following query
```yaml
{
  "type": "bulk",
  "args": [
    {
      "type": "create_remote_relationship",
      "args": {
        "name": "foo",
        .
        .
        "remote_field": {
          "hge_remote_addresses": {
            "arguments": {
              "where": {
                "_and": {
                  "id": {
                    "_eq": "$id"
                  },
                  "floor": {
                    "_eq": "$location_id"
                  }
                  .
                  .
}
```
The `_and` is generated as an object. It should  be an array
This gives the following error
```yaml
{
  "path": "$.args[0].args",
  "error": "ExpectedTypeButGot (TypeNamed (Nullability {unNullability = True}) (NamedType {unNamedType = Name {unName = \"String\"}})) (TypeNamed (Nullability {unNullability = True}) (NamedType {unNamedType = Name {unName = \"Int\"}})) :| []",
  "code": "remote-schema-error"
}
```
