### ISSUE TITLE
In remote relationship with nested fields, the parent fields should not be of type list

### ISSUE THREAD

**Issue by nizar-m** [tirumaraiselvan/graphql-engine#56]

**Comment by tirumaraiselvan** [comment]
@nizar-m Can you also describe the remote schema and the remote relationship to see this?

**Comment by nizar-m** [comment]
Let us say we have  `author ---remote arr_rel--> remote_articles ---obj_rel-->  publisher `. 
This should throw an error

```yaml
type: create_remote_relationship
args:
  name: nestedPublisher
  table: author
  hasura_fields:
   - id
   - publisher_ids 
  remote_schema: remote_articles
  remote_field:
     articles:
        arguments:
          author_id : $id
        field:
          remote_publisher:
            arguments:
              where:
                publisher_id:
                  _in: $publisher_ids
```
